### ISSUE TITLE
Upgrade issue in 2.0.6 [JIRA: CLIENTS-845]

### ISSUE THREAD

**Issue by jplock** [basho/riak-java-client#619]
I think you may be aware of this, but I wanted to let you know of an issue I ran into while upgrading from 2.0.5 to 2.0.6 within my Dropwizard 0.9.2 application.  Dropwizard 0.9.2 currently depends on Jackson 2.6.3 (and will be upgrading to Jackson 2.7.4 in Dropwizard 1.0.0).

As part of the Riak client 2.0.6 version, https://github.com/basho/riak-java-client/pull/615 upgraded Jackson to 2.7.3 which changed the method signature of `checkAndFixAccess` in `jackson-databind`, which resulted in a lot of these errors being thrown within my application (since I was creating a shaded-jar with Jackson 2.6.3 from Dropwizard taking precedence over Jackson 2.7.3 in the Riak client):

```
ERROR [2016-05-08 17:34:47,907] com.basho.riak.client.core.RiakNode: Operation onException() channel: id:-2069448905 127.0.0.1:8087 {}
    ! java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(Ljava/lang/reflect/Member;Z)V
    ! at com.basho.riak.client.api.convert.reflection.ClassUtil.checkAndFixAccess(ClassUtil.java:40) ~[notification-application-1.2.0.jar:1.2.0]
    ! at com.basho.riak.client.api.convert.reflection.AnnotationInfo$Builder.withRiakBucketNameField(AnnotationInfo.java:1240) ~[notification-application-1.2.0.jar:1.2.0]
```

Just pointing this out in case anyone else runs into this.  For the time being, I'm going to stick with the 2.0.5 Riak client when using Dropwizard 0.9.2 instead of messing around with my shaded jar settings.

**Comment by alexmoore** [comment]
Hey @jplock, thanks for reporting your issue.  We've thought of adding this to the list of shaded jars but it would add another 1M to the jar.  Do you know if this jackson api change is something a lot of people would run into?

Thanks,
Alex

**Comment by jplock** [comment]
It's hard to say.  I know that's a very recent version of Jackson.  Unless there was a reason to update Jackson, is it possible to downgrade it, or would you prefer if the dependencies are on the latest versions?

**Comment by alexmoore** [comment]
@jplock We bumped it during some spring cleaning of the dependencies and the pom.xml. Do you know if Dropwizard fixed the issue on their end?

Also would any of the proposed upgrades in #631 make you sad?

**Comment by jplock** [comment]
@alexmoore we're working on upgrading Dropwizard 1.0.0 to Jackson 2.8.0 as well (https://github.com/dropwizard/dropwizard/tree/issue-1627) so I think we'll be in alignment there.  We ran into a bunch of validation issues with 2.7.x

**Comment by alexmoore** [comment]
Ok, I'll look at the 2.8.0 version as well and close this ticket for now.

Thanks again!

**Comment by Basho-JIRA** [comment]
Will keep the Jackson version as-is, and will upgrade it to 2.8.0 in a future release. 

**_[posted via JIRA by Alexander Moore]**_
